export type BlogCategory =
  | "Chiropractic Approach"
  | "Chiropractic Care"
  | "Chiropractic Education"
  | "Chiropractic Treatment"
  | "Uncategorized";

export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  category: BlogCategory;
  /** Display date, e.g. "May 30, 2018" */
  date: string;
  /** ISO date for schema/<time>. */
  isoDate: string;
  /** Estimated read time, e.g. "4 min read" */
  readTime: string;
  /** Optional featured image URL. */
  featureImage: string | null;
};

export const CATEGORIES: BlogCategory[] = [
  "Chiropractic Approach",
  "Chiropractic Care",
  "Chiropractic Education",
  "Chiropractic Treatment",
  "Uncategorized",
];

export function categorySlug(c: BlogCategory): string {
  if (c === "Uncategorized") return "uncategorized";
  return c
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export const POSTS: BlogPost[] = [
  {
    slug: "two-reasons-you-should-not-supplement-with-vitamin-d",
    title: "Two Reasons You Should NOT Supplement with Vitamin D",
    excerpt: "I can only think of 2 reasons why a person should NOT supplement with Vitamin D.",
    category: "Uncategorized",
    date: "October 13, 2022",
    isoDate: "2022-10-13",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2022/10/ezgif.com-gif-maker-865x1024.png",
  },
  {
    slug: "covid-and-flu-prevention-that-you-need-to-know",
    title: "COVID and Flu Prevention That You Need to Know",
    excerpt: "For most of this year, your life has been inundated with the most important things that you need to know for COVID and the FLU. Things like social distancing, lockdowns, hand sanitizer, face masks. All of these things...",
    category: "Uncategorized",
    date: "October 27, 2020",
    isoDate: "2020-10-27",
    readTime: "3 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/10/COVID-supplements.jpg",
  },
  {
    slug: "temporary-closing-of-straight-chiropractic",
    title: "Temporary Closing of Straight Chiropractic",
    excerpt: "On March 24, 2020 Governor Michelle Lujan Grisham and Cabinet Secretary Kathyleen M. Kunkel issued a Public Health Order for the state of New Mexico. In order to be in compliance, Straight Chiropractic and The Neuropa...",
    category: "Uncategorized",
    date: "April 13, 2020",
    isoDate: "2020-04-13",
    readTime: "3 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/04/tempclose.jpg",
  },
  {
    slug: "the-most-important-covid-19-information",
    title: "The Most Important COVID-19 Information",
    excerpt: "Arguably, the most important COVID-19 information is probably not what you have been inundated with during the last few weeks.",
    category: "Uncategorized",
    date: "April 10, 2020",
    isoDate: "2020-04-10",
    readTime: "5 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/04/COVID-19.jpg",
  },
  {
    slug: "why-we-take-better-care-of-you-than-your-insurance",
    title: "Why We Take Better Care of You Than Your Insurance",
    excerpt: "First of all, we live in a transportation world that expects us to pay for the necessary maintenance on our vehicles. We have auto insurance that can replace our vehicle if it is damaged but, we pay for regular oil ch...",
    category: "Chiropractic Education",
    date: "May 23, 2019",
    isoDate: "2019-05-23",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/Health-insurance-money-1024x677.jpg",
  },
  {
    slug: "why-you-should-prevent-arthritis",
    title: "Why You Should Prevent Arthritis",
    excerpt: "The most common type of arthritis is osteoarthritis. According to the research it is a condition that is caused by repetitive strain/microtrauma and sedentary lifestyle. Also, it is understood that immobilization of t...",
    category: "Chiropractic Care",
    date: "May 9, 2019",
    isoDate: "2019-05-09",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/arthritis.jpg",
  },
  {
    slug: "how-to-reduce-the-risk-of-cancer-and-heart-disease-but-not-stroke",
    title: "How to Reduce the Risk of Cancer and Heart Disease But NOT Stroke",
    excerpt: "In November, 2018 the New England Journal of Medicine released a study that attempted to debunk the plethora of other studies that have shown the effectiveness of Fish oil and Vitamin D3 supplementation. In hopes to a...",
    category: "Uncategorized",
    date: "February 27, 2019",
    isoDate: "2019-02-27",
    readTime: "2 min read",
    featureImage: "/blog-images/how-to-reduce-the-risk-of-cancer-and-heart-disease-but-not-stroke.jpg",
  },
  {
    slug: "five-reasons-to-quit-sugar-now-2",
    title: "Five Reasons to Quit Sugar Now",
    excerpt: "Why it's so important to cut back on your sugar intake—and take back control of your health.",
    category: "Uncategorized",
    date: "November 26, 2018",
    isoDate: "2018-11-26",
    readTime: "3 min read",
    featureImage: "/blog-images/five-reasons-to-quit-sugar-now.jpg",
  },
  {
    slug: "3-keys-to-reducing-inflammation",
    title: "3 Keys to Reducing Inflammation",
    excerpt: "The 3 most important keys to reducing inflammation start with a clearer picture of why you have inflammation. Only then are you properly able to address it.",
    category: "Chiropractic Approach",
    date: "May 30, 2018",
    isoDate: "2018-05-30",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/Vitamin-D3.jpg",
  },
  {
    slug: "3-habits-to-improve-your-core-strength",
    title: "3 Habits to Improve Your Core Strength",
    excerpt: "There are 3 fundamental daily habits that will improve your core strength. But first it is important to discover why you should even be concerned about the strength of your core.",
    category: "Uncategorized",
    date: "April 2, 2018",
    isoDate: "2018-04-02",
    readTime: "2 min read",
    featureImage: "/blog-images/3-habits-to-improve-your-core-strength.avif",
  },
  {
    slug: "so-you-want-to-feel-better",
    title: "So You Want to Feel Better?",
    excerpt: "So you want to feel better but you don't know where to start. Perhaps it would be a good idea to do what Stephen Covey taught us, begin with the end in mind.",
    category: "Uncategorized",
    date: "March 22, 2018",
    isoDate: "2018-03-22",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/unnamed.jpg",
  },
  {
    slug: "are-you-heading-toward-an-early-death",
    title: "Are You Heading Toward an Early Death?",
    excerpt: "Is the path you are on taking you toward health, longevity and quality of life or toward an early death?",
    category: "Uncategorized",
    date: "March 14, 2018",
    isoDate: "2018-03-14",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/SHA-Score.jpg",
  },
  {
    slug: "please-dont-make-this-same-mistake",
    title: "Please Don't Make This Same Mistake…",
    excerpt: "I have a patient who came to see me the first time in February of 2005. He had never been to a chiropractor before. He was having some minor back pain. He had visible arthritis beginning but it was in the early stages...",
    category: "Uncategorized",
    date: "March 1, 2018",
    isoDate: "2018-03-01",
    readTime: "2 min read",
    featureImage: "/blog-images/please-dont-make-this-same-mistake.webp",
  },
  {
    slug: "8-ways-to-improve-your-sha-score",
    title: "8 Ways to Improve Your SHA Score!",
    excerpt: "Your Spinal Health Assessment (SHA) score is directly related to your level of health and wellness. If your SHA score is less than 90 it would be wise for you to work diligently at improving it. It can take 3 months o...",
    category: "Uncategorized",
    date: "February 26, 2018",
    isoDate: "2018-02-26",
    readTime: "2 min read",
    featureImage: "/blog-images/8-ways-to-improve-your-sha-score.webp",
  },
  {
    slug: "why-you-should-do-spinal-hygiene",
    title: "Why You Should Do Spinal Hygiene",
    excerpt: "Why should you do spinal hygiene and how often should you do it?",
    category: "Uncategorized",
    date: "February 26, 2018",
    isoDate: "2018-02-26",
    readTime: "2 min read",
    featureImage: "/blog-images/why-you-should-do-spinal-hygiene.avif",
  },
  {
    slug: "the-healthiest-chocolates-ever",
    title: "The Healthiest Chocolates Ever",
    excerpt: "Can chocolate really be healthy? It depends on the ingredients that go into them. Our ValenSpines chocolates are so healthy and tasty that you should eat several every day.",
    category: "Uncategorized",
    date: "February 26, 2018",
    isoDate: "2018-02-26",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/Chocolates-768x1024.jpg",
  },
  {
    slug: "the-number-one-reason-to-see-a-chiropractor",
    title: "The Number One Reason to See a Chiropractor",
    excerpt: "It is more than just a \"pop\", it is an on-going lifestyle of healthy choices!",
    category: "Uncategorized",
    date: "January 24, 2018",
    isoDate: "2018-01-24",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/article-1-2018.bmp",
  },
  {
    slug: "symptoms-or-causes-numbness-or-functional-restoration",
    title: "Symptoms or Causes—Numbness or Functional Restoration",
    excerpt: "It is easy to accept that when you have a tooth ache that you have a problem that is causing pain and that the pain is not the problem. The problem, whether it be a cracked tooth, decay or whatever, is the CAUSE of th...",
    category: "Uncategorized",
    date: "January 11, 2018",
    isoDate: "2018-01-11",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/Tooth-Ache-home-remedy.jpg",
  },
  {
    slug: "should-i-get-the-flu-shot",
    title: "Should I Get the Flu Shot?",
    excerpt: "The Flu is a respiratory infection that produces chills, fever, a sore throat, muscle aches and lasts about a week.",
    category: "Uncategorized",
    date: "January 10, 2018",
    isoDate: "2018-01-10",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/vaccines.jpg",
  },
  {
    slug: "vaccines-are-they-safe-and-effective",
    title: "Vaccines: Are They Safe and Effective?",
    excerpt: "The topic of vaccines and if they are safe and effective comes up quite frequently in my office. For some, this can be a very sensitive subject. Some parents claim that their child was indeed harmed by vaccines. Other...",
    category: "Uncategorized",
    date: "August 10, 2017",
    isoDate: "2017-08-10",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/vaccines.jpg",
  },
  {
    slug: "its-not-about-the-score",
    title: "It's Not About the Score",
    excerpt: "Do you remember what your most recent SHA (spinal health assessment) score is?",
    category: "Uncategorized",
    date: "June 26, 2017",
    isoDate: "2017-06-26",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/FullSizeRender-1024x576.jpg",
  },
  {
    slug: "should-we-trust-the-drugs-we-take",
    title: "Should We Trust the Drugs We Take?",
    excerpt: "Some governmental organizations are pressuring the FDA to approve drugs faster, but researchers at Yale found that nearly a third of all drugs approved between 2001 through 2010 had major safety issues after they were...",
    category: "Uncategorized",
    date: "June 19, 2017",
    isoDate: "2017-06-19",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/drugs.jpg",
  },
  {
    slug: "should-you-take-cholesterol-lowering-drugs",
    title: "Should You Take Cholesterol Lowering Drugs?",
    excerpt: "I frequently get asked the question, should I continue to take cholesterol lowering drugs, known as Statins?",
    category: "Uncategorized",
    date: "April 11, 2017",
    isoDate: "2017-04-11",
    readTime: "3 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/pills.jpg",
  },
  {
    slug: "do-painkillers-work-for-back-pain",
    title: "Do Painkillers Work for Back Pain?",
    excerpt: "Painkillers such as aspirin, Aleve and Advil don't help most people with back pain, a new review finds. The researchers estimated that only one in six people gained a benefit from taking these nonsteroidal anti-inflam...",
    category: "Uncategorized",
    date: "April 4, 2017",
    isoDate: "2017-04-04",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/painkillers-1024x751.jpg",
  },
  {
    slug: "do-you-have-movement-deficiency-syndrome",
    title: "Do you Have Movement Deficiency Syndrome?",
    excerpt: "If you don't exercise regularly you will have movement deficiency syndrome. But what is so wrong with that?",
    category: "Uncategorized",
    date: "March 21, 2017",
    isoDate: "2017-03-21",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/baby-doing-pushups.jpg",
  },
  {
    slug: "will-exercise-make-you-smarter",
    title: "Will Exercise Make you Smarter?",
    excerpt: "\"A study led by researchers at Columbia University provides the first evidence in humans that a structured exercise training program increases neurogenesis (the birth and development of new nerve cells) in a memory hu...",
    category: "Uncategorized",
    date: "March 8, 2017",
    isoDate: "2017-03-08",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/baby-squat.jpg",
  },
  {
    slug: "should-a-chiropractic-adjustment-hurt",
    title: "Should a Chiropractic Adjustment Hurt?",
    excerpt: "Should a Chiropractic adjustment hurt is one of the most common questions asked of me from new people in my office. Truthfully, sometimes a chiropractic adjustment can hurt. However, just because it hurts it does not...",
    category: "Uncategorized",
    date: "January 30, 2017",
    isoDate: "2017-01-30",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/download.jpg",
  },
  {
    slug: "should-your-chiropractor-prescribe-drugs",
    title: "Should Your Chiropractor Prescribe Drugs?",
    excerpt: "The question of whether or not your chiropractor should prescribe drugs may seem like a legitimate question to some. After all, you probably see your chiropractor more frequently than your MD. You probably have a bett...",
    category: "Uncategorized",
    date: "January 19, 2017",
    isoDate: "2017-01-19",
    readTime: "4 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/prescription-drugs.jpg",
  },
  {
    slug: "feeling-good-does-not-mean-you-are-healthy",
    title: "Feeling Good Does not Mean you are Healthy",
    excerpt: "I apologize in advance for the length of this article. Reading it to the end will help you determine if you are healthy or not.",
    category: "Uncategorized",
    date: "January 11, 2017",
    isoDate: "2017-01-11",
    readTime: "7 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/maxresdefault-1024x576.jpg",
  },
  {
    slug: "new-year-new-you-challenge",
    title: "New Year, New you Challenge",
    excerpt: "Do you hate New Year's Resolutions? I do too. But in 2016 I celebrated my 50th birthday. My health is very important to me so I set some health and fitness goals so that I could measure and then preserve my health for...",
    category: "Uncategorized",
    date: "December 21, 2016",
    isoDate: "2016-12-21",
    readTime: "3 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/IMG_3303-e1482279431235-1.jpg",
  },
  {
    slug: "did-chiropractic-care-cause-katie-mays-death",
    title: "Did Chiropractic Care Cause Katie May's Death?",
    excerpt: "Was the death of Katie May the result of Chiropractic? Numerous people have brought this to my attention and I felt it necessary to shed some evidence based light on the subject.",
    category: "Uncategorized",
    date: "November 18, 2016",
    isoDate: "2016-11-18",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/katie-may.jpg",
  },
  {
    slug: "how-to-make-your-core-strong",
    title: "How to Make Your Core Strong",
    excerpt: "It is important to understand how to make your core strong. The last couple articles I discussed the importance of a strong core. This article will discuss functional exercise and lifestyle as a means to create the st...",
    category: "Uncategorized",
    date: "November 15, 2016",
    isoDate: "2016-11-15",
    readTime: "3 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/abs-e1479252215517.jpg",
  },
  {
    slug: "would-you-shoot-a-cannon-from-a-canoe",
    title: "Would you Shoot a Cannon from a Canoe?",
    excerpt: "Would you want to shoot a cannon from a canoe or from a battleship? Seems like a silly question but work with me as I draw an analogy to your spinal health.",
    category: "Uncategorized",
    date: "November 7, 2016",
    isoDate: "2016-11-07",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/canoe-cannon-1024x585.jpg",
  },
  {
    slug: "how-many-pushups-can-you-do",
    title: "How Many Pushups Can you Do?",
    excerpt: "You know that exercise is good for you, but do you know where to start? Maybe you're self conscious about going to a gym and having people watch you. Pushups may just be your answer. They are perhaps nature's best exe...",
    category: "Uncategorized",
    date: "November 1, 2016",
    isoDate: "2016-11-01",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/pushups.jpg",
  },
  {
    slug: "how-long-does-it-take-to-brush",
    title: "How Long Does It Take to Brush?",
    excerpt: "As an adult I should have memories from 45 years ago of my parents or siblings brushing my teeth and helping me with my dental hygiene, but I don't. My children have those memories but I grew up in a time when the emp...",
    category: "Uncategorized",
    date: "October 25, 2016",
    isoDate: "2016-10-25",
    readTime: "3 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/plaque-1024x768.jpg",
  },
  {
    slug: "how-do-you-compare",
    title: "How Your Spinal Health Stacks Up: Patient Results at Synergy Spine",
    excerpt: "When I show people the results of their first Spinal Health Assessment they are often curious to see how much improvement is possible and how they compare to others. I do not believe it is healthy emotionally to compa...",
    category: "Uncategorized",
    date: "October 14, 2016",
    isoDate: "2016-10-14",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/IMG_1492-1-e1476465691373-1.jpg",
  },
  {
    slug: "are-you-fit-enough-to-be-president",
    title: "Are you Fit Enough to be President?",
    excerpt: "Back in August on his late night TV show, Jimmy Kimmel asked Hillary Clinton to open a jar of pickles in order to prove to Americans that she is fit enough to be the President of the United States. This article is in...",
    category: "Uncategorized",
    date: "October 11, 2016",
    isoDate: "2016-10-11",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/hilary-1024x578.jpg",
  },
  {
    slug: "whats-better-than-a-flu-shot",
    title: "What's Better than a Flu Shot?",
    excerpt: "There is so much controversy regarding flu shots. There are people and organizations on both sides of this controversy that are ready and eager to share their compelling \"evidence\" to support why they believe as they...",
    category: "Uncategorized",
    date: "October 5, 2016",
    isoDate: "2016-10-05",
    readTime: "2 min read",
    featureImage: "https://synergyspineandnerve.com/wp-content/uploads/2020/03/sugar.jpg",
  },
  {
    slug: "what-will-be-the-cause-of-your-death",
    title: "What Will be the Cause of Your Death?",
    excerpt: "Earlier this year the BMJ (formerly the British Medical Journal) published a paper that stated that medical errors are now the third leading cause of death in America, behind heart disease and cancer. The article was...",
    category: "Uncategorized",
    date: "July 25, 2016",
    isoDate: "2016-07-25",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "the-most-evidence-based-spinal-healthcare-protocol",
    title: "The Most Evidence Based Spinal Healthcare Protocol",
    excerpt: "For decades, the standard medical protocol for back pain is drugs or surgery. Yet medicine claims to be \"evidence based\" and many in the establishment are quick to report that Chiropractors are quacks and that nothing...",
    category: "Uncategorized",
    date: "March 16, 2016",
    isoDate: "2016-03-16",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "will-calcium-cause-heart-problems",
    title: "Will Calcium Cause Heart Problems?",
    excerpt: "Our society has been told that taking a calcium supplement is necessary in order to have strong healthy bones, especially if you are female and over the age of 50. Recent research shows that this path we have been on...",
    category: "Uncategorized",
    date: "January 20, 2016",
    isoDate: "2016-01-20",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "should-i-take-a-calcium-supplement",
    title: "Should I Take a Calcium Supplement?",
    excerpt: "Calcium supplementation is still a rather frequent prescription for people over 50 years of age, especially women. The thought is that older individuals tend to be at a higher risk of bone fractures, and since bone is...",
    category: "Uncategorized",
    date: "January 13, 2016",
    isoDate: "2016-01-13",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "use-the-hra-to-change-your-life",
    title: "Use the Hra to Change Your Life",
    excerpt: "The last article I wrote gave some New Year's Wisdom. You may recall:",
    category: "Uncategorized",
    date: "January 5, 2016",
    isoDate: "2016-01-05",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "new-years-resolution",
    title: "New Year's Resolution?",
    excerpt: "As we will shortly be embarking on a New Year it is a time to reflect on what we have accomplished in our lives and what we still want to accomplish. Unfortunately, many New Year's Resolutions are set with good intent...",
    category: "Uncategorized",
    date: "December 23, 2015",
    isoDate: "2015-12-23",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "i-got-worms",
    title: "How I Earned $60 Selling Worms As a 9-year-old",
    excerpt: "You may recognize that line from one of your favorite movies. In the movie it was intended to be much funnier than it has been in reality for me. Allow me to explain.",
    category: "Uncategorized",
    date: "December 2, 2015",
    isoDate: "2015-12-02",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "sitting-is-to-the-spine-as-sugar-is-to-the-teeth",
    title: "Sitting is to the Spine As Sugar is to the Teeth",
    excerpt: "We have been taught that eating sugar will cause tooth decay. The health of your teeth will improve when you eat less sugar. On the other hand, most of us are going to eat sugar so in order to keep our teeth healthy w...",
    category: "Uncategorized",
    date: "November 24, 2015",
    isoDate: "2015-11-24",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "symptoms-or-cause",
    title: "Toothache Symptoms Vs Causes: Identifying the Root Problem",
    excerpt: "It is easy to accept that when you have a tooth ache that you have a problem that is causing pain and that the pain is not the problem. The problem, whether it be a cracked tooth, decay or whatever, is the CAUSE of th...",
    category: "Uncategorized",
    date: "November 18, 2015",
    isoDate: "2015-11-18",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "health-tip-of-the-day-should-i-get-the-flu-shot",
    title: "Health Tip of the Day: Should I Get the Flu Shot?",
    excerpt: "What is the Flu? The Flu is a respiratory infection that produces chills, fever, a sore throat, muscle aches and lasts about a week.",
    category: "Uncategorized",
    date: "November 9, 2015",
    isoDate: "2015-11-09",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "liquid-vs-gel-cap-fish-oil-which-should-i-take",
    title: "Liquid Vs. Gel Cap Fish Oil Which Should I Take?",
    excerpt: "Is there really a difference in taking liquid verses a gel capsule fish oil supplement? Trying to decide which one you should take can be a difficult dilemma.",
    category: "Uncategorized",
    date: "October 29, 2015",
    isoDate: "2015-10-29",
    readTime: "2 min read",
    featureImage: "https://www.straightchiro.com/wp-content/uploads/2015/10/liquidfishoil-300x300.jpg",
  },
  {
    slug: "try-eating-this-healthy-dessert-for-breakfast",
    title: "Try Eating This Healthy Dessert…for Breakfast!",
    excerpt: "I eat in a manner that will build my cells and help me express great health while allowing myself to not feel guilty when I occasionally deviate.",
    category: "Uncategorized",
    date: "October 1, 2015",
    isoDate: "2015-10-01",
    readTime: "2 min read",
    featureImage: "https://www.straightchiro.com/wp-content/uploads/2015/10/coconutmilk-300x200.jpg",
  },
  {
    slug: "happy-birthday-bj-palmer",
    title: "Happy Birthday Bj Palmer",
    excerpt: "Monday, September 14th would have been B.J. Palmer's 133rd birthday. B.J. is considered the developer of Chiropractic. His father D.D. Palmer was the founder and with his first adjustment restored the hearing of Harve...",
    category: "Uncategorized",
    date: "September 14, 2015",
    isoDate: "2015-09-14",
    readTime: "2 min read",
    featureImage: "https://www.straightchiro.com/wp-content/uploads/2015/09/bj_palmer-224x300.jpg",
  },
  {
    slug: "will-calcium-prevent-osteoporosis",
    title: "Will Calcium Prevent Osteoporosis?",
    excerpt: "So many people supplement with calcium in hopes to prevent osteoporosis. Is this something that is necessary?",
    category: "Uncategorized",
    date: "September 8, 2015",
    isoDate: "2015-09-08",
    readTime: "2 min read",
    featureImage: "https://www.straightchiro.com/wp-content/uploads/2015/09/calcium-osteoporosis-chiropractic-300x169.jpg",
  },
  {
    slug: "why-would-you-want-to-take-fish-oil",
    title: "Why Would you Want to Take Fish Oil?",
    excerpt: "There is really only one reason you would ever want to take fish oil….",
    category: "Uncategorized",
    date: "August 31, 2015",
    isoDate: "2015-08-31",
    readTime: "2 min read",
    featureImage: "https://www.straightchiro.com/wp-content/uploads/2015/08/fish-oil-chiropractic-supplement-300x290.jpg",
  },
  {
    slug: "do-you-need-to-take-vitamin-d-2",
    title: "Do You Need to Take Vitamin D?",
    excerpt: "There are folks today that say you do not need to take vitamin D. This is surprising to me given the mountain of evidence that points the other way.",
    category: "Uncategorized",
    date: "August 24, 2015",
    isoDate: "2015-08-24",
    readTime: "4 min read",
    featureImage: null,
  },
  {
    slug: "are-multi-vitamins-essential",
    title: "Are Multi Vitamins Essential?",
    excerpt: "The most common supplement taken by people are multi vitamins. Are they really essential for good health? In other words, can you be healthy without taking a multi vitamin every day?",
    category: "Uncategorized",
    date: "August 10, 2015",
    isoDate: "2015-08-10",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "why-do-you-take-that",
    title: "Why do you Take That?",
    excerpt: "The majority of people that come into our office are taking supplements, some sort of multi vitamins being the most common. However, most people don't really know why they are taking them and unfortunately, some are e...",
    category: "Uncategorized",
    date: "August 4, 2015",
    isoDate: "2015-08-04",
    readTime: "2 min read",
    featureImage: "https://www.straightchiro.com/wp-content/uploads/2015/08/pills-300x127.jpg",
  },
  {
    slug: "get-rid-of-your-pain-2",
    title: "Get Rid of Your Pain",
    excerpt: "You want to get rid of your pain, right? The information in this article will help you get rid of pain sooner and help it stay away.",
    category: "Uncategorized",
    date: "July 30, 2015",
    isoDate: "2015-07-30",
    readTime: "3 min read",
    featureImage: null,
  },
  {
    slug: "your-yellow-jersey",
    title: "Claim Your Health's Yellow Jersey with Synergy Spine & Nerve Center",
    excerpt: "The Tour de France is far from a casual ride through the park. 198 riders lined up this year on the 4th of July to race just under 2,100 miles in 3 weeks. Out of those select 198 racers, only one will rise to the top...",
    category: "Uncategorized",
    date: "July 22, 2015",
    isoDate: "2015-07-22",
    readTime: "2 min read",
    featureImage: "https://www.straightchiro.com/wp-content/uploads/2015/07/straight-chiropractic-yellow-jersey-300x187.jpg",
  },
  {
    slug: "are-you-taking-vitamin-d",
    title: "Are you Taking Vitamin D?",
    excerpt: "You probably already know that you get vitamin D from the sun. That's how our ancestors got it. Unfortunately the research is evident that the majority of people are deficient.",
    category: "Chiropractic Education",
    date: "May 26, 2015",
    isoDate: "2015-05-26",
    readTime: "2 min read",
    featureImage: "https://www.straightchiro.com/wp-content/uploads/2015/05/vitamin-d3.jpg",
  },
  {
    slug: "the-essential-nutrient-vitamin-d",
    title: "The Essential Nutrient, Vitamin D",
    excerpt: "The term \"essential\" nutrient means that it is absolutely required for the optimal expression of health in the cells and there must be an external source of that nutrient. In other words, it must be ingested through f...",
    category: "Chiropractic Education",
    date: "March 31, 2015",
    isoDate: "2015-03-31",
    readTime: "2 min read",
    featureImage: "https://www.straightchiro.com/wp-content/uploads/2015/03/vitamin-d.jpg",
  },
  {
    slug: "drug-free-chiropractic-sb376",
    title: "Drug Free Chiropractic Sb376",
    excerpt: "There are a few outspoken Chiropractors in our state that would like to change the scope of Chiropractic to include the ability to prescribe medication. There is currently a piece of legislation that if it passes woul...",
    category: "Uncategorized",
    date: "February 12, 2015",
    isoDate: "2015-02-12",
    readTime: "3 min read",
    featureImage: null,
  },
  {
    slug: "are-you-the-special",
    title: "Are you the Special?",
    excerpt: "I am a fan of the Lego Movie. It was fun, entertaining and taught positive moral values.",
    category: "Uncategorized",
    date: "October 30, 2014",
    isoDate: "2014-10-30",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "why-eat-grass-fed-beef",
    title: "Why Eat Grass Fed Beef",
    excerpt: "Grass fed beef costs more than grain fed beef. So is the health difference between the 2 types of beef really worth the cost? The answer for me is an emphatic yes but you shouldn't take my word for it.",
    category: "Uncategorized",
    date: "October 29, 2014",
    isoDate: "2014-10-29",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "3-annoying-workplace-habits-to-kick",
    title: "3 Annoying Workplace Habits to Kick",
    excerpt: "Lets face it: The groove we fall into at work can often be less than perfect. When you're spending more than 40 hours a week at the office, it's no wonder you've developed and overlooked some of your workplace habits....",
    category: "Uncategorized",
    date: "August 5, 2014",
    isoDate: "2014-08-05",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "chiroopractors-and-injection-for-back-pain",
    title: "Chiroopractors and Injection for Back Pain",
    excerpt: "A severe back pain can create debilitating effects on a person's quality of life. The reaasons for back pain may be several – sedentary life style, non-ergonomic furniture, sports injuries or even accidents. However,...",
    category: "Chiropractic Treatment",
    date: "July 9, 2014",
    isoDate: "2014-07-09",
    readTime: "2 min read",
    featureImage: "https://www.straightchiro.com/wp-content/uploads/2014/07/back_pain.jpg",
  },
  {
    slug: "3-reasons-you-may-need-a-chiropractor-in-rio-rancho",
    title: "3 Reasons you May Need a Chiropractor in Rio Rancho",
    excerpt: "Going to a chiropractor can be one of the most relaxing things you've done in a longtime. There are many reasons to go see a chiropractor in Rio Rancho. Here are the 3 top reasons why you should:",
    category: "Chiropractic Approach",
    date: "June 19, 2014",
    isoDate: "2014-06-19",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "three-keys-to-finding-a-chiropractor-in-rio-rancho",
    title: "Three Keys to Finding a Chiropractor in Rio Rancho",
    excerpt: "Most people don't consider these three keys to finding a Chiropractor in Rio Rancho.",
    category: "Chiropractic Approach",
    date: "November 1, 2013",
    isoDate: "2013-11-01",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "melt-away-your-stress-with-chiropractic-care",
    title: "Melt Away Your Stress with Chiropractic Care",
    excerpt: "In today's hectic world it is easy to become stressed. Work and school are fast paced and competitive and in the current financial climate it can be difficult to earn the amount needed to give your family the lifestyl...",
    category: "Chiropractic Treatment",
    date: "September 9, 2013",
    isoDate: "2013-09-09",
    readTime: "4 min read",
    featureImage: null,
  },
  {
    slug: "how-to-find-the-best-chiropractor-in-rio-rancho",
    title: "How to Find the Best Chiropractor in Rio Rancho?",
    excerpt: "The 2 most important questions to ask yourself when you are looking for the best Rio Rancho Chiropractor for you are: Will they get the Results you are looking for and Will you be able to maintain those results.",
    category: "Chiropractic Care",
    date: "August 28, 2013",
    isoDate: "2013-08-28",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "doctored-movie-night",
    title: "Doctored Movie Night",
    excerpt: "Join us for Movie Night, complete with Popcorn on July 30th, Tuesday evening at 5:30",
    category: "Chiropractic Approach",
    date: "July 17, 2013",
    isoDate: "2013-07-17",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "4-tips-to-finding-the-best-chiropractor-for-you-in-rio-rancho",
    title: "4 Tips to Finding the Best Chiropractor for you in Rio Rancho",
    excerpt: "You want to make sure you find the best Chiropractor for you in Rio Rancho when you are hurting. And when you are hurting, you don't have time to be put on a waiting list and actually get help a few weeks from now. Yo...",
    category: "Chiropractic Care",
    date: "July 5, 2013",
    isoDate: "2013-07-05",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "how-chiropractic-care-benefits-the-entire-family",
    title: "How Chiropractic Care Benefits the Entire Family",
    excerpt: "When it comes to caring for your family, many people don't consider chiropractic treatment to benefit the entire family and their health. Everybody is able to benefit greatly from chiropractic treatment, whether it's...",
    category: "Chiropractic Care",
    date: "May 14, 2013",
    isoDate: "2013-05-14",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "what-is-the-first-thing-that-comes-to-mind-when-you-think-of-liver",
    title: "What Is the First Thing That Comes to Mind When You Think of Liver?",
    excerpt: "Do your olfactory receptors trigger memories of liver and onions frying in a pan at grandma's house?",
    category: "Chiropractic Education",
    date: "2013-04-04",
    isoDate: "2018-01-01",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "forget-cholesterol-inflammation-is-the-real-cause-of-heart-disease",
    title: "Forget Cholesterol, Inflammation Is the Real Cause of Heart Disease",
    excerpt: "It's time to forget the Cholesterol and begin to address the inflammation that is the real cause of heart disease.",
    category: "Chiropractic Education",
    date: "2013-03-19",
    isoDate: "2018-01-01",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "sb471-drugs-for-new-mexico-chiropractors",
    title: "SB471-Drugs for New Mexico Chiropractors?",
    excerpt: "Do you think that Chiropractors, with their limited education, should be able to prescribe drugs?",
    category: "Chiropractic Care",
    date: "2013-02-13",
    isoDate: "2018-01-01",
    readTime: "4 min read",
    featureImage: null,
  },
  {
    slug: "griego-family-thank-you",
    title: "Griego Family, Thank You",
    excerpt: "There is absolutely no excuse for the actions of a 15-year-old boy killing his own family. This has been more than just a shocking event for our community.",
    category: "Uncategorized",
    date: "2013-01-24",
    isoDate: "2018-01-01",
    readTime: "3 min read",
    featureImage: null,
  },
  {
    slug: "high-fructose-corn-syrup-just-how-bad-is-it",
    title: "High Fructose Corn Syrup: Just How Bad Is It?",
    excerpt: "High Fructose Corn Syrup (HFCS) is in almost EVERYTHING these days. There are many pros and cons that can be debated around this topic and according to the HFCS sponsored website \"it's okay\" but they do state, it is,...",
    category: "Chiropractic Care",
    date: "2012-10-31",
    isoDate: "2018-01-01",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "are-you-addicted-to-sugar",
    title: "Are You Addicted to Sugar?",
    excerpt: "Sugar is in ALMOST everything we eat. Breads, cereals, beverages, every sauce you can think of and with Halloween, Thanksgiving and Christmas just around the corner there is no end. It is no wonder the fall months kic...",
    category: "Chiropractic Care",
    date: "2012-10-25",
    isoDate: "2018-01-01",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "what-you-need-to-know-about-arsenic-found-in-rice",
    title: "What You Need to Know About Arsenic Found in Rice",
    excerpt: "There has been increasing concern about the amount of arsenic in rice products, especially when it comes to rice products for youngsters.",
    category: "Chiropractic Education",
    date: "2012-10-20",
    isoDate: "2018-01-01",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "does-chiropractic-enhance-immune-function",
    title: "Does Chiropractic Enhance Immune Function?",
    excerpt: "The immune system performs a very complex part of your overall health. We all know the immune system is what protects us from the \"terrible germs\" of the cold and flu. It protects us from disease and even protects us...",
    category: "Chiropractic Care",
    date: "2012-10-16",
    isoDate: "2018-01-01",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "are-vaccinations-safe",
    title: "Are Vaccinations Safe?",
    excerpt: "The safety of vaccines has been in question and is a hot topic causing controversy between governments, parents, children and wellness advocates.",
    category: "Chiropractic Care",
    date: "2012-10-10",
    isoDate: "2018-01-01",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "posture-exercises-for-kids",
    title: "Posture Exercises for Kids",
    excerpt: "Here in Albuquerque school will be starting today, in Rio Rancho in a couple of weeks. With students going back to school means long hours sitting, carrying a heavy backpack, returning to sports activities and increas...",
    category: "Chiropractic Approach",
    date: "2012-09-29",
    isoDate: "2018-01-01",
    readTime: "2 min read",
    featureImage: "https://www.straightchiro.com/wp-content/uploads/2012/09/posture.jpg",
  },
  {
    slug: "tips-on-backpack-safety-for-kids",
    title: "Tips on Backpack Safety for Kids",
    excerpt: "Summer is almost over, back-to-school shopping is unavoidable and the endless backpack options can be a real pain in the neck. Backpacks are a necessity in the everyday life of a student, but used improperly a backpac...",
    category: "Chiropractic Care",
    date: "2012-08-08",
    isoDate: "2018-01-01",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "barack-obama-on-health-care-plan",
    title: "Barack Obama on Health Care Plan",
    excerpt: "Obamacare, National Health Care for everyone. Is it really FREE.",
    category: "Chiropractic Education",
    date: "2012-07-13",
    isoDate: "2018-01-01",
    readTime: "4 min read",
    featureImage: null,
  },
  {
    slug: "why-you-should-live-like-a-chicken",
    title: "Why you Should Live Like a Chicken?",
    excerpt: "I am surprised when I visit with people to see just how many people have poor sleep quality and are not able to sleep well.",
    category: "Chiropractic Approach",
    date: "June 22, 2012",
    isoDate: "2012-06-22",
    readTime: "4 min read",
    featureImage: null,
  },
  {
    slug: "necessity-of-chiropractic-care-after-a-car-accident",
    title: "Necessity of Chiropractic Care After a Car Accident",
    excerpt: "Do you need to seek out Chiropractic Care following an automobile accident?",
    category: "Chiropractic Treatment",
    date: "June 8, 2012",
    isoDate: "2012-06-08",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "long-drives-and-chiropractic-care",
    title: "Long Drives and Chiropractic Care",
    excerpt: "Long drives and chiropractic care go hand in hand. When taking that cross country summer vacation do you begin to notice that if your breaks are far apart exiting, the car you feel one thousand years old? Well maybe n...",
    category: "Chiropractic Care",
    date: "June 4, 2012",
    isoDate: "2012-06-04",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "truth-about-gluten-free-foods-and-type-1-diabetes",
    title: "Truth About Gluten-free Foods and Type 1 Diabetes",
    excerpt: "Gluten is a protein found in wheat, rye, barley and all foods containing these grains. Research was done which concluded that the protein gluten, which is the known causative agent in celiac disease is also a trigger...",
    category: "Chiropractic Education",
    date: "May 23, 2012",
    isoDate: "2012-05-23",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "breast-cancer-prevention-tips",
    title: "Breast Cancer Prevention Tips",
    excerpt: "Considering that breast cancer is now one of the most commonly diagnosed cancers on the planet, simple interventions like this one could save countless numbers of lives. A recent report adds to the growing evidence th...",
    category: "Chiropractic Education",
    date: "May 15, 2012",
    isoDate: "2012-05-15",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "symptoms-of-hormonal-imbalance-in-women",
    title: "Symptoms of Hormonal Imbalance in Women",
    excerpt: "Hormonal imbalance can be one of the many causes of many of the frustrations in a woman's life. These hormone imbalances are not due to monthly cycles but due to higher levels of stress, and fatigue. In this day and a...",
    category: "Chiropractic Education",
    date: "May 2, 2012",
    isoDate: "2012-05-02",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "too-much-texting-linked-to-health-risks",
    title: "Too Much Texting Linked to Health Risks",
    excerpt: "Texting health risks being addressed in Chiropractic clinics across the nation is devastatingly on the rise. In 2008 the Smartphone outsold the laptop computer for the first time ever. Hand-held or mobile devices have...",
    category: "Chiropractic Education",
    date: "April 21, 2012",
    isoDate: "2012-04-21",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "take-my-headache-away",
    title: "Take My Headache Away",
    excerpt: "A lady came into my office last week and said \"Take my headache away.\" She was looking for a miracle because of how much pain she was in.",
    category: "Chiropractic Treatment",
    date: "March 6, 2012",
    isoDate: "2012-03-06",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "heres-to-a-great-2012",
    title: "Here's to a Great 2012",
    excerpt: "It's a brand new year. Have you taken the time to reflect on what you want in 2012?",
    category: "Uncategorized",
    date: "January 3, 2012",
    isoDate: "2012-01-03",
    readTime: "2 min read",
    featureImage: null,
  },
  {
    slug: "merry-christmas",
    title: "Wishing you a Merry Christmas from Synergy Spine and Nerve Center",
    excerpt: "We at Straight Chiropractic wanted to take a moment and share our gratitude for you in trusting our office with your health. We recognize that your health is your greatest asset and you take it seriously and so do we.",
    category: "Uncategorized",
    date: "December 19, 2011",
    isoDate: "2011-12-19",
    readTime: "2 min read",
    featureImage: null,
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return POSTS.find((p) => p.slug === slug);
}

export function getPostsByCategory(slug: string): BlogPost[] {
  return POSTS.filter((p) => categorySlug(p.category) === slug);
}

export function getCategoryBySlug(slug: string): BlogCategory | undefined {
  return CATEGORIES.find((c) => categorySlug(c) === slug);
}

/** Backwards-compat alias for the older typo */
export const getCategoryByslug = getCategoryBySlug;

export function getRelatedPosts(slug: string, limit = 3): BlogPost[] {
  const cur = getPostBySlug(slug);
  if (!cur) return POSTS.slice(0, limit);
  const sameCat = POSTS.filter((p) => p.slug !== slug && p.category === cur.category);
  if (sameCat.length >= limit) return sameCat.slice(0, limit);
  const others = POSTS.filter((p) => p.slug !== slug && p.category !== cur.category);
  return [...sameCat, ...others].slice(0, limit);
}
